// export const baseURL: string = 'http://localhost:8080/';
export const RES_CODE = '000000';
export const baseURL: string = '/api';
export const LOGIN:string = '/user/login'
export const GET_USER_LIST:string = '/user/getUserList'
export const DELETE_USER:string = '/user/deleteUser'
export const ADD_USER:string = '/user/addUser'
export const UPDATE_USER_LOCK:string = '/user/updateLock'
export const RESET_USER_PASSWORD:string = '/user/resetPassword'
export const ROLE_LIST_URL:string = '/systemRole/getSystemRoleList'
export const ADD_ROLE_URL:string = '/systemRole/addSystemRole'
export const UPDATE_ROLE_URL:string = '/systemRole/updateSystemRole'
export const DELETE_ROLE_URL:string = '/systemRole/deleteSystemRole'
export const UPDATE_ROLE_USER_URL:string = '/user/updateRoleUser'
export const GET_MANICURE_LIST_URL:string = '/manicure/getManicureList'
export const UPLOAD_URL:string = '/comont/upload'
export const ADD_MANICURE_URL:string = '/manicure/addManicure'
export const UPDATE_MANICURE_URL:string = '/manicure/updateManicure'
export const DELETE_MANICURE_URL:string = '/manicure/deleteManicure'
